@echo off
cd /d "%~dp0.."
if not defined AMADEUS_BACKEND_PORT set AMADEUS_BACKEND_PORT=3001
if not defined AMADEUS_FLOAT_AUTOSTART set AMADEUS_FLOAT_AUTOSTART=0
if not defined AMADEUS_FLOAT_START_HIDDEN set AMADEUS_FLOAT_START_HIDDEN=0
if not defined AMADEUS_FLOAT_HOTKEY set AMADEUS_FLOAT_HOTKEY=Alt+Shift+K
npm start
